version: 0.2

phases:
  install:
    commands:
      - printenv
      - pip install mkdocs
      - pip install mkdocs-macros-plugin
      - pip install mkdocs-material
  build:
    commands:
      - cd ./metadata/
      - git remote add gh-token "https://${GH_TOKEN}@https://github.com/tjtjtjtj/catalog-page.git"
      - git fetch gh-token && git fetch gh-token gh-pages:gh-pages
      - cd docs && mkdocs gh-deploy -v --clean --remote-name gh-token -b gh-pages --force
