version: 0.2

phases:
  install:
    commands:
      - printenv
      - pip install mkdocs
      - pip install mkdocs-macros-plugin
      - pip install mkdocs-material
  build:
    commands:
      - cd ./metadata/
      - mkdocs gh-deploy