version: 0.2

phases:
  install:
    commands:
      - printenv
      - pip install mkdocs
      - pip install mkdocs-macros-plugin
      - pip install mkdocs-material
  build:
    commands:
      - ls -ltra
      - mkdir tmp && cd tmp
      - git clone "https://${GH_TOKEN}@github.com/tjtjtjtj/catalog-page.git" 
      - cd catalog-page/metadata
      - git remote add gh-token "https://${GH_TOKEN}@github.com/tjtjtjtj/catalog-page.git"
      - mkdocs gh-deploy -v --clean --remote-name gh-token -b gh-pages --force
